[package]
name = "albumpaper_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
rayon = "1.5.1"
fastblur = { git = "https://github.com/fschutt/fastblur" }
ordered-float = { version = "3.0", default-features = false }
fast_image_resize = "2.7.3"

# Colored noise
colorgrad = "0.6.2"
noise = "0.8.2"
imageproc = "0.23.0"

[lib]
name = "albumpaper_rs"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.18.2"
features = ["extension-module"]
